services:
  fastapi:
    build:
      context: .  # Build from the current directory
    ports:
      - "8000:8000"  # Map port 8000 of the container to port 8000 on the host
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
