name: Lint with Ruff

on:
  push:
    branches:
      - '**'  # This will trigger the action on any branch
  pull_request:
    branches:
      - '**'  # This will trigger the action on any pull request to any branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff
      run: ruff .
